### PR TITLE
Use official markdown license for AGPLv3.

### PR DESCRIPTION
**Pull request by iphydf**
Taken from https://www.gnu.org/licenses/agpl-3.0.md

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/github-tools/66)

### CODE REVIEW

**Comment by robinlinden** [comment]
:lgtm_strong:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/github-tools/66#-:-KaFMdJzzlI-RKGj81gi:b-jbsf8z)*

**Comment by piling** [comment]
:lgtm_strong:

---

Reviewed 2 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/github-tools/66#-:-KaIjDWgeIR70BIjJgWQ:b-jbsf8z)*

**Comment by fcore117** [comment]
Reviewed 2 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/github-tools/66)*

**Comment by robinlinden** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/github-tools/66)*

**Pull request merged**
