### PR TITLE
Rename references of admin_approved to adminApproved in reviewable.js.

### PR DESCRIPTION
**Pull request by iphydf**
This change is [Reviewable](https://reviewable.io/reviews/toktok/github-tools/55)

### CODE REVIEW

**Comment by robinlinden** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/github-tools/55#-:-K_zVvPCDe345WALG6-r:b-jbsf8z)*

**Comment by cebe** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/github-tools/55#-:-K_zd7v3EImrn4onlpRK:b-jbsf8z)*

**Comment by robinlinden** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/github-tools/55)*

**Comment by cebe** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/github-tools/55)*

**Pull request merged**
