### PR TITLE
Create reviewable_script.js

### PR DESCRIPTION
**Pull request by GrayHatter**
This is a completion for @reviewable created to ensure good reviews across all Tox repos.

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/github-tools/40)

### CODE REVIEW

**Comment by iphydf** [comment]
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions.

---

*[reviewable_script.js, line 17 at r1](https://reviewable.io:443/reviews/toktok/github-tools/40#-K_RQjcttomry2Am4EqX:-K_RQjcttomry2Am4EqY:b-mlpn2f) ([raw file](https://github.com/toktok/github-tools/blob/1881bb27740c690c3ca35dbd4b715d404911396d/reviewable_script.js#L17)):*
> ```JavaScript
> // Part 1 Check that each file has been reviewed by at least numReviewersRequired at the latest revision.
> const unreviewedFiles = _(review.files)
>                          .filter(file => _.size(_.last(file.revisions).reviewers) <= numReviewersRequired)
> ```

Inconsistent hanging indentation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/github-tools/40)*

**Comment by iphydf** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/github-tools/40)*

**Comment by GrayHatter** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[reviewable_script.js, line 14 at r1](https://reviewable.io:443/reviews/toktok/github-tools/40#-K_RPuKtreFUfLt5JrBe:-K_RWCtD9k3O4Htriqmb:buoyf1o) ([raw file](https://github.com/toktok/github-tools/blob/1881bb27740c690c3ca35dbd4b715d404911396d/reviewable_script.js#L14)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

Why 1 less? It's unintuitive and therefore needs a comment, but why is it necessary to be unintuitive in the first place?
</blockquote></details>

I've made a change that if memory serves didn't work the last time I tried it, but I've since cleaned up more of the source, so we'll try it again.

---

*[reviewable_script.js, line 17 at r1](https://reviewable.io:443/reviews/toktok/github-tools/40#-K_RQjcttomry2Am4EqX:-K_RX2EUhV1bhOrPiiin:b-896fix) ([raw file](https://github.com/toktok/github-tools/blob/1881bb27740c690c3ca35dbd4b715d404911396d/reviewable_script.js#L17)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

Inconsistent hanging indentation.
</blockquote></details>

Done.

---

*[reviewable_script.js, line 74 at r1](https://reviewable.io:443/reviews/toktok/github-tools/40#-K_RQQcX_-pNh77VB3Gw:-K_RXCbjLxQ1KROjisyJ:b-896fix) ([raw file](https://github.com/toktok/github-tools/blob/1881bb27740c690c3ca35dbd4b715d404911396d/reviewable_script.js#L74)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

Camel case.
</blockquote></details>

Done.

---

*[reviewable_script.js, line 90 at r1](https://reviewable.io:443/reviews/toktok/github-tools/40#-K_RQ7FgSfm3HPHkmldF:-K_RXYQIhs28c5uR7ICE:b-896fix) ([raw file](https://github.com/toktok/github-tools/blob/1881bb27740c690c3ca35dbd4b715d404911396d/reviewable_script.js#L90)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

```js
const s = unresolvedDiscussions.length == 1 ? '' : 's';
descriptionPieces.push(`${unresolvedDiscussions.length} open discussion${s} remaining`);
```
</blockquote></details>

Done.

---

*[reviewable_script.js, line 101 at r1](https://reviewable.io:443/reviews/toktok/github-tools/40#-K_RQ4jQorFLpqEpkSz7:-K_RXazkFBgzuOK6nYim:b-896fix) ([raw file](https://github.com/toktok/github-tools/blob/1881bb27740c690c3ca35dbd4b715d404911396d/reviewable_script.js#L101)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

Lowercase `missing`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/github-tools/40)*

**Comment by iphydf** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[reviewable_script.js, line 14 at r2](https://reviewable.io:443/reviews/toktok/github-tools/40#-K_kMtXv_6jC-IbDlxoI:-K_kMtXv_6jC-IbDlxoJ:bs3ouem) ([raw file](https://github.com/toktok/github-tools/blob/1a662df42eacf47dad0641d43c5462cc4f6376de/reviewable_script.js#L14)):*
> ```JavaScript
> 
> 
> const numReviewersRequired = 3; // TODO do we want to calculate this number by size of diff, or number of files?
> ```

`TODO(grayhatter): do we ...`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/github-tools/40)*

**Comment by iphydf** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/github-tools/40#-:-K_kN3wkPMlmUO7yQGGQ:b-jbsf8z)*

**Comment by GrayHatter** [comment]
Once @robinlinden or @zer0-one signoff I'll squash/rebase

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[reviewable_script.js, line 14 at r2](https://reviewable.io:443/reviews/toktok/github-tools/40#-K_kMtXv_6jC-IbDlxoI:-K_mv1RHEdlaJ2CSnmmN:b-1b9oy7) ([raw file](https://github.com/toktok/github-tools/blob/1a662df42eacf47dad0641d43c5462cc4f6376de/reviewable_script.js#L14)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

`TODO(grayhatter): do we ...`
</blockquote></details>

Done.

But IMO, we don't really need to do that, because `git blame` is a thing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/github-tools/40#-:-K_mv7uvd4t1KU2f2WGm:bbkos9n)*

**Comment by Zer0-One** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/github-tools/40#-:-K_nQXmeAcalmNQYKrgh:b-jbsf8z)*

**Comment by robinlinden** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/github-tools/40#-:-K_oyB8d3Sp6WHRZYJXo:b-jbsf8z)*

**Pull request merged**
